GET http://localhost:5000

POST http://localhost:5000/add
Content-Type: application/json

{
  "Title": "Assasin's Creed IV Black Flag",
  "Id": 1
}

PUT http://localhost:5000/update
Content-Type: application/json

{
  "Id": 1,
  "Title": "Assasin's Creed II"
}

DELETE http://localhost:5000/del?id=5
Content-Type: application/json


